version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-timescaledb}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: ./.env
    depends_on:
      - backend
    

  backend:
    build: ./backend
    env_file: ./.env
    environment:
      - GIN_MODE=release
    ports:
      - "3001:3001"
    depends_on:
      - timescaledb