version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-timescaledb}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
volumes:
  timescale_data: